[package]
name = "lanshare-core"
version = "0.1.0"
edition = "2024"

[dependencies]
lanshare-proto = { path = "../lanshare-proto" }
uuid = { version = "1.18.1", features = ["v4"] }
# tokio = { version = "1.47.1", default-features = false, features = ["macros", "rt-multi-thread", "net"] }

